apiVersion: v1
kind: Service
metadata:
  name: jenkinsproject-service
spec:
  type: NodePort
  selector:
    app: jenkinsproject
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30082
